package main

import (
	"log"
	"os"

	"github.com/joho/godotenv"

	"stock/api"

	// Swagger docs
	_ "stock/docs" // Import Swagger docs generated by swag init

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Stock Market API
// @version 1.0
// @description API for retrieving time series data from stock markets

// @contact.name API Support
// @contact.email admin@example.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /
// @schemes http
func main() {
	// Load environment variables from .env file
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, using environment variables")
	}

	// Get port from environment or use default
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// Setup router
	router := api.SetupRouter()

	// Setup Swagger endpoints
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start server
	log.Printf("Starting server on port %s\n", port)
	log.Printf("Swagger UI available at http://localhost:%s/swagger/index.html\n", port)
	if err := router.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
