basePath: /
definitions:
  api.BalanceSheetResponse:
    description: Balance sheet response data structure
    properties:
      data:
        $ref: '#/definitions/fundamental.BalanceSheetResponse'
      symbol:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  api.CashFlowResponse:
    description: Cash flow response data structure
    properties:
      data:
        $ref: '#/definitions/fundamental.CashFlowResponse'
      symbol:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  api.TimeSeriesResponse:
    description: Time series response data structure
    properties:
      data:
        additionalProperties: true
        type: object
      interval:
        type: string
      symbol:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  fundamental.BalanceSheetReport:
    properties:
      accumulatedDepreciationAmortizationPPE:
        type: string
      capitalLeaseObligations:
        type: string
      cashAndCashEquivalentsAtCarryingValue:
        type: string
      cashAndShortTermInvestments:
        type: string
      commonStock:
        type: string
      commonStockSharesOutstanding:
        type: string
      currentAccountsPayable:
        type: string
      currentDebt:
        type: string
      currentLongTermDebt:
        type: string
      currentNetReceivables:
        type: string
      deferredRevenue:
        type: string
      fiscalDateEnding:
        type: string
      goodwill:
        type: string
      intangibleAssets:
        type: string
      intangibleAssetsExcludingGoodwill:
        type: string
      inventory:
        type: string
      investments:
        type: string
      longTermDebt:
        type: string
      longTermDebtNoncurrent:
        type: string
      longTermInvestments:
        type: string
      otherCurrentAssets:
        type: string
      otherCurrentLiabilities:
        type: string
      otherNonCurrentAssets:
        type: string
      otherNonCurrentLiabilities:
        type: string
      propertyPlantEquipment:
        type: string
      reportedCurrency:
        type: string
      retainedEarnings:
        type: string
      shortLongTermDebtTotal:
        type: string
      shortTermDebt:
        type: string
      shortTermInvestments:
        type: string
      totalAssets:
        type: string
      totalCurrentAssets:
        type: string
      totalCurrentLiabilities:
        type: string
      totalLiabilities:
        type: string
      totalNonCurrentAssets:
        type: string
      totalNonCurrentLiabilities:
        type: string
      totalShareholderEquity:
        type: string
      treasuryStock:
        type: string
    type: object
  fundamental.BalanceSheetResponse:
    properties:
      annualReports:
        items:
          $ref: '#/definitions/fundamental.BalanceSheetReport'
        type: array
      quarterlyReports:
        items:
          $ref: '#/definitions/fundamental.BalanceSheetReport'
        type: array
      symbol:
        type: string
    type: object
  fundamental.CashFlowReport:
    properties:
      capitalExpenditures:
        type: string
      cashflowFromFinancing:
        type: string
      cashflowFromInvestment:
        type: string
      changeInCashAndCashEquivalents:
        type: string
      changeInExchangeRate:
        type: string
      changeInInventory:
        type: string
      changeInOperatingAssets:
        type: string
      changeInOperatingLiabilities:
        type: string
      changeInReceivables:
        type: string
      depreciationDepletionAndAmortization:
        type: string
      dividendPayout:
        type: string
      dividendPayoutCommonStock:
        type: string
      dividendPayoutPreferredStock:
        type: string
      fiscalDateEnding:
        type: string
      netIncome:
        type: string
      operatingCashflow:
        type: string
      paymentsForOperatingActivities:
        type: string
      paymentsForRepurchaseOfCommonStock:
        type: string
      paymentsForRepurchaseOfEquity:
        type: string
      paymentsForRepurchaseOfPreferredStock:
        type: string
      proceedsFromIssuanceOfCommonStock:
        type: string
      proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet:
        type: string
      proceedsFromIssuanceOfPreferredStock:
        type: string
      proceedsFromOperatingActivities:
        type: string
      proceedsFromRepaymentsOfShortTermDebt:
        type: string
      proceedsFromRepurchaseOfEquity:
        type: string
      proceedsFromSaleOfTreasuryStock:
        type: string
      profitLoss:
        type: string
      reportedCurrency:
        type: string
    type: object
  fundamental.CashFlowResponse:
    properties:
      annualReports:
        items:
          $ref: '#/definitions/fundamental.CashFlowReport'
        type: array
      quarterlyReports:
        items:
          $ref: '#/definitions/fundamental.CashFlowReport'
        type: array
      symbol:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: admin@example.com
    name: API Support
  description: API for retrieving time series data from stock markets
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Stock Market API
  version: "1.0"
paths:
  /api/v1/fundamental/balance-sheet/{symbol}:
    get:
      description: Returns the balance sheet data for the specified stock symbol
      parameters:
      - description: Stock symbol (e.g., AAPL, MSFT)
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/api.BalanceSheetResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get balance sheet data for a specific symbol
      tags:
      - fundamental
  /api/v1/fundamental/cash-flow/{symbol}:
    get:
      description: Returns the cash flow data for the specified stock symbol
      parameters:
      - description: Stock symbol (e.g., AAPL, MSFT)
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/api.CashFlowResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get cash flow data for a specific symbol
      tags:
      - fundamental
  /api/v1/timeseries/{symbol}:
    get:
      description: Returns time series data for the specified stock symbol
      parameters:
      - description: Stock symbol (e.g., AAPL, MSFT)
        in: path
        name: symbol
        required: true
        type: string
      - default: TIME_SERIES_DAILY
        description: Time series function
        enum:
        - TIME_SERIES_DAILY
        - TIME_SERIES_WEEKLY
        - TIME_SERIES_MONTHLY
        in: query
        name: function
        type: string
      - default: compact
        description: Amount of data to return
        enum:
        - compact
        - full
        in: query
        name: outputsize
        type: string
      - default: json
        description: Data type for response
        enum:
        - json
        - csv
        in: query
        name: datatype
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/api.TimeSeriesResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get time series data for a specific symbol
      tags:
      - timeseries
  /api/v1/timeseries/{symbol}/{interval}:
    get:
      description: Returns intraday time series data with the specified interval
      parameters:
      - description: Stock symbol (e.g., AAPL, MSFT)
        in: path
        name: symbol
        required: true
        type: string
      - description: Time interval for data
        enum:
        - 1min
        - 5min
        - 15min
        - 30min
        - 60min
        in: path
        name: interval
        required: true
        type: string
      - default: compact
        description: Amount of data to return
        enum:
        - compact
        - full
        in: query
        name: outputsize
        type: string
      - default: json
        description: Data type for response
        enum:
        - json
        - csv
        in: query
        name: datatype
        type: string
      - default: false
        description: Whether to include extended hours data
        in: query
        name: extended_hours
        type: boolean
      - default: true
        description: Whether to adjust for split and dividend events
        in: query
        name: adjusted
        type: boolean
      - description: Month for historical intraday data (YYYY-MM format)
        in: query
        name: month
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/api.TimeSeriesResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get intraday time series data with specific interval
      tags:
      - timeseries
schemes:
- http
swagger: "2.0"
